sudo: false
cache:
- pip
language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - pypy

env:
- FLASK=0.10.1
- FLASK=0.10

install:
  - pip install -U setuptools pep8 six coverage docutils pygments flask==$FLASK

script:
  - coverage erase
  - nosetests --with-coverage --cover-package=flask_cors
  - python setup.py clean build install

after_success:
  - pep8 flask_cors.py

deploy:
  provider: pypi
  user: CoryDolphin
  password:
    secure: c/z1OYmniNlJ7F7G+TipOlJfVLCEz0F09JCJJ4+TPB/DTxajxarMEygX/LrvBOLvbe1EvAKO9p/SOagAul00YXU/rb2i1k1tJnKF2A6KKSLOsZbTcGWNcInOaLKql4Cv8Ts1cOfMiTVHBQLR+1FCw+IuZ44N+KhF0tsFOejEmRc=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: corydolphin/flask-cors
    condition: $TRAVIS_PYTHON_VERSION != *2.6* # Ensures we release a 2.7X wheel
